- index.ts
> remove enCaseCode from TJDTO cause is in DecisionDTO

- README.md
- index.ts
> Handle zoning on txt and pseudotxt

- index.ts
- package.json
> feat - adding new labelStatus for labelStatusCompute function

- index.ts
> fix : add array to zoningZones

- index.ts
> labelStatus update : codeNacObsolete --> blocOcculationNonDefini

- index.ts
> add motivationOccultation on decision occultation

- index.ts
> originalTextZoning is optional in type

- index.ts
> feat : add recommandation occultation non suivie  in labelStatuses

- index.ts
> add missing TypePartie for TCOM ("NA")

- index.ts
Ajout d'une extension du modèle de décision pour les TCOM (pas trop le choix). Pas certain de l'impact (ou de ce que cela nécessite de faire) au niveau de l'API DBSDER.
> feat: add DecisionTCOMDTO

- index.ts
> fix composition zoning type

- index.ts
> feat new label status IGNORED_JURIDICTION_EN_PHASE_DE_TEST

- index.ts
> selection field for all sources, not only for TJ and TCOM

- tsconfig.json
> fix useless exclude

- src/typeGuards/decisions_tj.zod.ts
- src/types/decisions_tj.ts
> fix: publishDate can be null

- src/typeGuards/common.zod.ts
- src/typeGuards/decisions_ca.zod.ts
- src/typeGuards/decisions_cc.zod.ts
- src/typeGuards/decisions_tcom.zod.ts
- src/typeGuards/decisions_tj.zod.ts
- src/typeGuards/index.ts
- src/types/common.ts
- src/types/decisions_ca.ts
- src/types/decisions_cc.ts
- src/types/decisions_tcom.ts
- src/types/decisions_tj.ts
- src/types/index.ts
> fix: dbsder-api-types doesn't hide errors

- src/typeGuards/index.ts
- Sinon ==> version patch
La génération et la mise a jour du token npmjs est géré par [Paul Déchorgnat](https://github.com/pauldechorgnat) et [Antoine Jeanneney](https://github.com/ajeanneney).
> patch: add errors stringify

- src/typeGuards/index.ts
- Sinon ==> version patch
La génération et la mise a jour du token npmjs est géré par [Paul Déchorgnat](https://github.com/pauldechorgnat) et [Antoine Jeanneney](https://github.com/ajeanneney).
> fix: parse error

- src/typeGuards/decisions_cc.zod.ts
- src/types/decisions_cc.ts
- Sinon ==> version patch
La génération et la mise a jour du token npmjs est géré par [Paul Déchorgnat](https://github.com/pauldechorgnat) et [Antoine Jeanneney](https://github.com/ajeanneney).
> fix: analysis undefined over null

- src/types/common.ts
- src/types/index.ts
- Sinon ==> version patch
La génération et la mise a jour du token npmjs est géré par [Paul Déchorgnat](https://github.com/pauldechorgnat) et [Antoine Jeanneney](https://github.com/ajeanneney).
> export some types related to NLP
